version: '3.9'

services:

  server:
    build:
      context: server
    ports:
      - "5000"


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    ports:
      - "80:80"