version: '3.9'

services:

  server:
    build:
      context: server
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: arxiv_database
      DB_USER: arxiv_user
      DB_PASSWORD: arxiv_password
    depends_on:
      - postgres
    ports:
      - "5000"

  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: arxiv_database
      POSTGRES_USER: arxiv_user
      POSTGRES_PASSWORD: arxiv_password
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    ports:
      - "80:80"